### ISSUE TITLE
vonmises_std

### ISSUE THREAD

**Issue by hvasbath** [williamjameshandley/spherical_kde#1]
First of all I wanted to thank you for your awesome code and the effort you put into that!

I noticed that you maybe by accident switched phi and theta, to the input of VanMises here:
https://github.com/williamjameshandley/spherical_kde/blob/ea4fed3bb43c21b14c1e62fd583760a2e424efb4/spherical_kde/__init__.py#L71

Maybe thats the reason why your std estimation maybe performing poorly as you wrote in the readme- or is it switched on purpose?

**Comment by williamjameshandley** [comment]
Hi @hvasbath. Many thanks for spotting this -- you are indeed correct that those arguments are transposed (which I have corrected in #2). It turns out that for the examples here there is little difference.

The 'rough and ready' bandwidth estimation refers to the fact that there isn't really any statistical theory specific to the spherical case that's been put into this, it's mostly in analogy to the non-spherical case.
